import {useEffect,useRef,useState} from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {ArrowUpRight,Command,Scan,X,Search,ArrowRight,Check,ChevronDown,Code2,Braces,Layers,Workflow,Database,Sparkles} from 'lucide-react';
import {AnimatedLink} from './components/AnimatedLink';
import {NumberFlow} from './components/NumberFlow';
const skills=[
 {id:'fullstack',name:'Full-stack development',ko:'제품 전체를 연결하는 개발',tag:'FULL-STACK',desc:'사용자가 만나는 화면부터 API, 데이터와 운영까지. 한 부분의 완성도를 넘어 제품 전체의 흐름을 설계합니다.',points:['프론트엔드와 백엔드를 연결하는 설계','사용성과 유지보수성을 함께 고려','배포 이후의 운영까지 이어지는 개발']},
 {id:'ai',name:'LLM & AI in practice',ko:'실제로 쓰이는 AI',tag:'LLM / AI',desc:'LLM과 AI를 개발 과정과 제품에 활용합니다. 기술 자체보다 실제 업무에서 줄어드는 반복과 사용자가 얻는 가치를 먼저 봅니다.',points:['업무 흐름에 맞는 LLM 활용','AI를 활용한 개발 생산성 개선','품질·응답 속도·비용을 함께 고려']},
 {id:'technology',name:'Modern technology',ko:'새로운 기술, 필요한 곳에',tag:'MODERN TECH',desc:'최신 기술을 빠르게 익히고 제품의 맥락에 맞게 적용합니다. 도입 효과와 복잡도를 비교해 오래 운영할 수 있는 선택을 합니다.',points:['새로운 기술의 빠른 검증','문제에 맞는 기술 선택','도입 비용과 유지보수성 검토']},
 {id:'cost',name:'Practical cost optimization',ko:'비용까지 설계하는 개발',tag:'EFFICIENCY',desc:'인프라와 AI 사용 비용을 제품 설계의 일부로 봅니다. 꼭 필요한 품질을 지키면서 실제 운영 부담을 줄이는 방법을 찾습니다.',points:['불필요한 호출과 반복 작업 줄이기','캐싱과 리소스 사용 구조 검토','품질과 운영 비용 사이의 균형']},
 {id:'leadership',name:'Team leadership',ko:'팀이 함께 잘 만드는 방법',tag:'TEAM LEAD',desc:'방향을 정리하고 기술적 의사결정을 공유합니다. 리뷰와 협업을 통해 개인의 경험이 팀의 실행력으로 이어지도록 돕습니다.',points:['목표와 우선순위 정리','코드 리뷰와 기술 지식 공유','팀의 자율성과 실행력 지원']},
 {id:'experience',name:'10+ years of experience',ko:'경험으로 더 단단하게',tag:'10+ YEARS',desc:'10년 이상의 개발 경험을 바탕으로 복잡한 문제를 풀어냅니다. 무엇을 만들지뿐 아니라 왜 만들고 어떻게 운영할지 함께 생각합니다.',points:['문제의 본질을 찾는 접근','제품 관점의 기술적 의사결정','개발부터 운영까지 연결하는 경험']},
 {id:'delivery',name:'From idea to production',ko:'아이디어를 실제 제품으로',tag:'DELIVERY',desc:'아이디어를 작은 단위로 검증하고 실제로 사용할 수 있는 제품으로 구체화합니다. 구현과 피드백을 연결해 다음 단계를 결정합니다.',points:['요구사항을 구현 가능한 단위로 정리','빠른 검증과 점진적인 개선','운영을 고려한 제품 완성']},
 {id:'detail',name:'Details that matter',ko:'작은 차이까지 만드는 개발',tag:'CRAFT',desc:'화면의 반응과 인터랙션, 코드의 구조까지. 사용하기 좋고 함께 발전시키기 좋은 제품을 지향합니다.',points:['명확한 인터페이스와 자연스러운 반응','반응형 화면과 접근성','읽기 쉽고 확장 가능한 코드']}
];
function App(){
 const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState<number|null>(null),[optimized,setOptimized]=useState(false),[aiStep,setAiStep]=useState(0);
 const dialog=useRef<HTMLDialogElement>(null);const reduced=useReducedMotion();
 const modalOpen=search||selected!==null;
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(s=>!s);setSelected(null)}if(e.key==='Escape'){setMenu(false);setSearch(false);setSelected(null)}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[]);
 useEffect(()=>{if(modalOpen){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[modalOpen]);
 const navigate=(href:string)=>{setSearch(false);setMenu(false);setSelected(null);requestAnimationFrame(()=>document.querySelector(href)?.scrollIntoView({behavior:reduced?'instant':'smooth'}))};
 const reveal={initial:reduced?false:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-40px'},transition:{duration:.65}};
 return <><a className="skip-link" href="#main">본문으로 이동</a><header className="nav"><a className="brand" href="#"><span className="orb"/>WAYVE</a><nav aria-label="주요 메뉴"><a href="#approach">Approach</a><a href="/wayve/components">Components</a></nav><button className="icon-button" aria-label="검색 열기 Command K" onClick={()=>setSearch(true)}><Command size={18}/></button><button className="icon-button" aria-label={menu?'메뉴 닫기':'메뉴 열기'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={19}/>:<Scan size={19}/>}</button>{menu&&<div className="menu-panel">{[['ABOUT','#about','10+ years'],['COMPONENTS','/wayve/components','103 live demos'],['APPROACH','#approach','How I work'],['GITHUB','https://github.com/sixun','sixun']].map(([name,href,hint])=><a href={href} key={name} onClick={()=>setMenu(false)}>{name}<span>[{hint}]</span><ArrowUpRight size={20}/></a>)}<p>FULL-STACK DEVELOPER · LLM & AI</p></div>}</header>
 <main id="main"><section className="hero" id="about"><div className="hero-copy"><p className="eyebrow">WAYVE / SIXUN</p><h1 aria-label="Un-common Developer">{['UN-COMMON','DEVELOPER'].map((line,l)=><span className="hero-line" aria-hidden="true" key={line}>{line.split('').map((letter,i)=><motion.span key={i} initial={reduced?false:{y:110,opacity:0,rotateX:-80}} animate={{y:0,opacity:1,rotateX:0}} transition={{duration:.8,delay:.05*i+l*.14,ease:[.16,1,.3,1]}} whileHover={reduced?{}:{y:-10,color:'#0077ff'}}>{letter}</motion.span>)}</span>)}</h1><p className="eyebrow">FULL-STACK · LLM & AI · 10+ YEARS</p></div><div className="hero-actions"><a className="intro-chip" href="#expertise"><span>10년+ 경험,</span> 기술을 실제 가치로 <ArrowRight size={14}/></a><a className="primary-button" href="/wayve/components">Explore components <ArrowUpRight size={15}/></a></div></section>
 <section id="expertise" className="expertise"><motion.div {...reveal} className="section-title"><h2>10+ Years. Beyond the stack.</h2><p>풀스택 개발부터 AI 활용, 비용 최적화, 팀 리딩까지.<br/>제품의 시작과 성장에 필요한 경험을 연결합니다.</p></motion.div><div className="bento">
 {skills.map((s,i)=><motion.article {...reveal} className={`tile tile-${i}`} key={s.id}><div className={`demo demo-${i}`}><span className="demo-mark"><Sparkles size={13}/></span>
 {i===0&&<div className="stack-visual"><div><Code2/>Interface</div><span>↓</span><div><Braces/>API & Logic</div><span>↓</span><div><Database/>Data</div></div>}
 {i===1&&<button className="ai-demo" onClick={()=>setAiStep((aiStep+1)%3)} aria-label="AI 활용 단계 전환"><div className="mini-tabs">{['THINK','BUILD','SHIP'].map((x,k)=><span className={k===aiStep?'active':''} key={x}>{x}</span>)}</div><motion.strong key={aiStep} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>{['AI.','BUILD.','SHIP.'][aiStep]}</motion.strong><small>{['가능성을 발견하고','실제로 구현하고','제품의 가치로 연결합니다'][aiStep]} ↗</small></button>}
 {i===2&&<div className="technology-visual">{[Code2,Database,Workflow,Braces,Layers,Sparkles,Code2,Workflow].map((Icon,k)=><motion.div key={k} drag dragSnapToOrigin dragConstraints={{top:-20,left:-20,right:20,bottom:20}} whileHover={{scale:1.1}} className={'tech-icon tech-'+k}><Icon size={37}/></motion.div>)}<small>DRAG TO EXPLORE</small></div>}
 {i===3&&<div className="cost-demo"><span className="micro-label">LESS WASTE. MORE VALUE.</span><strong>{optimized?'Lean.':'Cost.'}</strong><button aria-pressed={optimized} onClick={()=>setOptimized(!optimized)}><span className={'toggle '+(optimized?'on':'')}/>{optimized?'필요한 만큼, 효율적으로':'불필요한 비용 줄이기'}</button><div className={'cost-bars '+(optimized?'optimized':'')}>{[1,2,3,4,5,6,7,8].map(x=><i key={x} style={{height:25+x*6}}/>)}</div></div>}
 {i===4&&<div className="lead-visual"><div className="island"><i/><span>Building together</span><span className="wave">▂▅▃▇▅</span></div><div className="team-letters">{['방향','리뷰','성장'].map(x=><span key={x}>{x}</span>)}</div><p>Better, together.</p></div>}
 {i===5&&<div className="experience-demo"><NumberFlow value={10} suffix="+"/><span>YEARS OF BUILDING</span></div>}
 {i===6&&<div className="delivery-visual"><div><span>Idea</span><ArrowRight/><span>Build</span><ArrowRight/><span className="ship">Ship <Check size={12}/></span></div><p>Make it real.</p></div>}
 {i===7&&<div className="detail-visual"><span className="detail-cross">+</span><span className="detail-circle"/><strong>Details.</strong><span className="detail-caption">작은 차이가 만드는 완성도</span></div>}
 </div><button className="tile-caption" onClick={()=>setSelected(i)}>{s.name}<ArrowUpRight size={16}/></button></motion.article>)}
 </div><div className="center-link"><AnimatedLink href="/wayve/components">Explore all 103 components</AnimatedLink></div></section>
 <motion.section {...reveal} className="statement"><span className="pill">ENGINEERING WITH INTENT</span><p>기술을 위한 기술보다,<br/><span>실제로 도움이 되는 개발.</span></p><div>10년 이상의 경험에 새로운 기술의 가능성을 더합니다.<br/>만드는 과정도, 운영하는 비용도, 함께하는 팀도 생각합니다.</div><AnimatedLink href="https://github.com/sixun">GitHub / sixun</AnimatedLink></motion.section>
 <section className="principles" id="approach"><motion.div {...reveal} className="section-title"><h2>Good software.<br/>Great teamwork.</h2><p>좋은 제품은 코드와 사람, 판단이 함께 만듭니다.</p></motion.div><div className="principle-frame"><div className="frame-heading"><span>✳</span> HOW I WORK <span>✳</span></div><div className="principle-row"><span>01</span><h3>Understand the problem.</h3><p>해결해야 할 문제와 우선순위부터 명확하게.</p></div><div className="principle-row"><span>02</span><h3>Choose with purpose.</h3><p>최신 기술도 품질·비용·운영의 관점에서.</p></div><div className="principle-row"><span>03</span><h3>Build together.</h3><p>생각을 공유하고, 팀과 함께 완성도를 높이기.</p></div><div className="frame-heading bottom">TOOLS ARE A MEANS. VALUE IS THE GOAL.</div><div className="stack-tags">{['Full-stack','LLM & AI','Modern tech','Cost optimization','Team leadership'].map(x=><span key={x}>{x}</span>)}</div></div></section>
 <section className="focus-section"><motion.div {...reveal} className="section-title"><h2>One developer.<br/>A wider perspective.</h2><p>개발의 깊이와 제품을 보는 넓은 시야.</p></motion.div><div className="focus-cards">{[['01','Build.','제품을 만드는 힘','Frontend / Backend'],['02','Optimize.','실질적인 효율을 만드는 판단','AI / Cost / Operations'],['03','Lead.','함께 성장하는 팀','Direction / Review / Growth']].map(([n,title,ko,tag])=><motion.a {...reveal} href="#expertise" className={'focus-card focus-'+n} key={n}><span>SIXUN_{n}</span><strong>{title}</strong><div>{ko}<small>{tag}</small></div><ArrowUpRight/></motion.a>)}</div></section>
 <section className="collaboration"><motion.div {...reveal} className="section-title"><h2>From the first idea<br/>to the next chapter.</h2><p>새로운 제품도, 다음 단계로의 성장도.</p></motion.div><div className="collab-grid">{[['Product engineering','제품을 실제로.',['풀스택 제품 개발','LLM·AI 기능 활용','사용성과 운영을 고려한 설계'],'#expertise'],['Technical leadership','팀과 함께, 더 멀리.',['기술 방향과 우선순위 정리','실질적인 비용 최적화','팀 리딩과 개발 문화 개선'],'#approach']].map(([title,sub,items,href])=><article key={title as string}><span>{title}</span><h3>{sub}</h3><ul>{(items as string[]).map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><a className="primary-button" href={href as string}>자세히 보기 <ArrowUpRight size={16}/></a></article>)}</div></section>
 <footer id="contact"><motion.div {...reveal}><span className="pill">LET'S BUILD</span><h2>Build something<br/>that matters.</h2><p>실제 가치를 만드는 개발자, sixun.</p><AnimatedLink href="https://github.com/sixun">Meet me on GitHub</AnimatedLink></motion.div><div className="footer-art" aria-hidden="true"><img className="hand left" src="/wayve/media/cdn/images/footer/LeftHand.webp" alt="" loading="lazy"/><div className="seal"><span>SIXUN · FULL STACK ·</span><i className="orb"/></div><img className="hand right" src="/wayve/media/cdn/images/footer/RightHand.webp" alt="" loading="lazy"/></div><div className="footer-credit">©sixun <a href="#">Back to top ↑</a></div></footer>
 </main><dialog ref={dialog} className="dialog" onCancel={()=>{setSearch(false);setSelected(null)}} onClick={e=>{if(e.target===e.currentTarget){setSearch(false);setSelected(null)}}}><div className="dialog-content"><button className="close-button icon-button" aria-label="닫기" onClick={()=>{setSearch(false);setSelected(null)}}><X size={20}/></button>{search?<><h2>빠르게 이동하기</h2><div className="search-input"><Search size={18}/><input autoFocus placeholder="역량, AI, 비용, 팀 리딩 검색" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>ESC</kbd></div><div className="search-results">{skills.filter(s=>(s.name+s.ko+s.desc).toLowerCase().includes(query.toLowerCase())).map(s=><button key={s.id} onClick={()=>{setSearch(false);setSelected(skills.indexOf(s))}}>{s.ko}<ArrowUpRight size={16}/></button>)}{skills.filter(s=>(s.name+s.ko+s.desc).toLowerCase().includes(query.toLowerCase())).length===0&&<p>검색 결과가 없습니다. 다른 키워드를 입력해 주세요.</p>}</div><button className="text-button" onClick={()=>navigate('#approach')}>협업 방식으로 이동 <ChevronDown size={15}/></button></>:selected!==null?<><span className="pill">{skills[selected].tag}</span><h2>{skills[selected].ko}</h2><p>{skills[selected].desc}</p><ul>{skills[selected].points.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><AnimatedLink href="https://github.com/sixun">GitHub에서 더 보기</AnimatedLink></>:null}</div></dialog></>
}
export default App;
