import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Search,RotateCcw,PanelLeft,Maximize,Minimize,Sun,Moon,X} from 'lucide-react';
import catalogue from './catalogue.json';
import './gallery.css';
const groups:[string,number[]][]=[['New Releases',[105,106,107]],['Out of the box',[1,2,5,24,29,73,76,80,96,101]],['Minimal interactions',[3,4,25,26,27,37,40,42,58,61,63,64,66,68,69,70,72,86,87,99,103]],['Crazy Hover',[6,18,35,52,53,59,90]],['Preloaders',[7,8,9,10,11,15]],['Crazy Hero',[12,14,36,39]],['Navigation',[13,38,57,75]],['Scroll Effects',[16,17,19,28,30,31,32,33,34,55,60,71,74,79,88,89,94,95,104]],['Web3',[20,21,22,23,45]],['Blur & Detail',[41,44,56]],['Menus & Tooltips',[43,46,92,98,100]],['Carousels',[47,48,49,50,51,54,77,78]],['Development tools',[62,65,102]],['Video Players',[67,91,97]],['AI Input',[81,82,83,84,85]]];
const missing=[12,14,36];
const items=catalogue.map(c=>({...c,category:groups.find(g=>g[1].includes(c.id))?.[0]||'Components',available:!missing.includes(c.id)}));
function PreviewCard({item}:{item:typeof items[number]}){const video=useRef<HTMLVideoElement>(null);return <a className="component-card" href={`/v1/skiper${item.id}`} onMouseEnter={()=>video.current?.play().catch(()=>{})} onMouseLeave={()=>video.current?.pause()} onFocus={()=>video.current?.play().catch(()=>{})} onBlur={()=>video.current?.pause()}><div className="card-preview"><img src={item.image||undefined} alt="" loading="lazy"/>{item.video&&<video ref={video} src={item.video} muted loop playsInline preload="none"/>}<span className={'availability '+(!item.available?'unavailable':'')}>{item.available?'TRY IT':'준비 중'}</span><span className="preview-open"><ArrowUpRight size={20}/></span></div><div className="component-card-title"><span>{item.name}</span><small>#{item.id.toString().padStart(3,'0')}</small></div></a>}
export default function Gallery(){const currentId=Number(location.pathname.match(/\/v1\/skiper(\d+)/)?.[1]);const current=items.find(x=>x.id===currentId);const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[sort,setSort]=useState('category'),[sidebar,setSidebar]=useState(false),[revision,setRevision]=useState(0),[fullscreen,setFullscreen]=useState(false),[dark,setDark]=useState(false);const stage=useRef<HTMLDivElement>(null);const input=useRef<HTMLInputElement>(null);const filtered=items.filter(i=>(i.name+' '+i.id+' '+i.category).toLowerCase().includes(query.toLowerCase())&&(category==='All'||i.category===category));
 useEffect(()=>{document.title=current?`${current.name} — sixun Playground`:'Components — sixun Playground';const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSidebar(true);requestAnimationFrame(()=>input.current?.focus())}if(e.key==='Escape')setSidebar(false)};const full=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('keydown',key);document.addEventListener('fullscreenchange',full);return()=>{document.removeEventListener('keydown',key);document.removeEventListener('fullscreenchange',full)}},[current]);
 async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.current?.requestFullscreen()}catch{setFullscreen(false)}}
 if(location.pathname.startsWith('/v1/')&&!current)return <div className="gallery-empty"><h1>컴포넌트를 찾을 수 없습니다.</h1><a href="/components">전체 목록으로</a></div>;
 if(current){const index=items.indexOf(current),previous=items[(index-1+items.length)%items.length],next=items[(index+1)%items.length];return <div className={'playground '+(dark?'playground-dark':'')}><aside className={'play-sidebar '+(sidebar?'open':'')}><div className="sidebar-brand"><a href="/" className="brand"><span className="orb"/>SIXUN</a><button onClick={()=>setSidebar(false)} aria-label="목록 닫기"><X size={18}/></button></div><a href="/components" className="back-gallery"><ArrowLeft size={14}/> All components <span>106</span></a><label className="gallery-search"><Search size={16}/><input ref={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search components"/></label><div className="sidebar-scroll">{groups.map(([name,ids])=>{const rows=filtered.filter(i=>ids.includes(i.id));return rows.length>0&&<section key={name}><h2>{name}</h2>{rows.map(i=><a key={i.id} href={`/v1/skiper${i.id}`} className={i.id===current.id?'selected':''}><span>{i.name}</span><small>{i.available?i.id:'준비 중'}</small></a>)}</section>})}</div></aside>{sidebar&&<button className="sidebar-scrim" aria-label="목록 닫기" onClick={()=>setSidebar(false)}/>}
 <div ref={stage} className="play-stage"><div className="play-toolbar"><button title="컴포넌트 목록" aria-label="컴포넌트 목록" onClick={()=>setSidebar(!sidebar)}><PanelLeft size={18}/></button><a href="/components" className="play-breadcrumb">Components <span>/ {current.name}</span></a><div className="play-actions"><button title="테마 전환" aria-label="테마 전환" onClick={()=>{setDark(!dark);const frame=stage.current?.querySelector('iframe');frame?.contentWindow?.postMessage({type:'demo-theme',theme:!dark?'dark':'light'},location.origin)}}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button title="다시 실행" aria-label="다시 실행" onClick={()=>setRevision(revision+1)}><RotateCcw size={17}/></button><button title="전체 화면" aria-label="전체 화면" onClick={toggleFullscreen}>{fullscreen?<Minimize size={17}/>:<Maximize size={17}/>}</button></div></div>
 {current.available?<iframe key={current.id+'-'+revision} title={`${current.name} interactive demo`} src={`/demo/skiper${current.id}?theme=${dark?'dark':'light'}`} sandbox="allow-scripts allow-same-origin" allow="fullscreen"/>:<div className="gallery-empty"><span className="pill">#{current.id}</span><h1>{current.name}</h1><p>원본 사이트 오류로 소스를 확보하지 못한 데모입니다.</p><a href={`/v1/skiper${next.id}`}>다음 컴포넌트 보기 <ArrowRight size={16}/></a></div>}
 <div className="play-bottom"><a href={`/v1/skiper${previous.id}`} aria-label="이전 컴포넌트"><ArrowLeft size={16}/></a><span>{current.name}<small>#{current.id} · 직접 클릭하고 스크롤해 보세요</small></span><a href={`/v1/skiper${next.id}`} aria-label="다음 컴포넌트"><ArrowRight size={16}/></a></div></div></div>}
 return <><header className="nav"><a className="brand" href="/"><span className="orb"/>SIXUN</a><nav aria-label="주요 메뉴"><a href="/">Portfolio</a><a aria-current="page" href="/components">Components</a></nav><button className="icon-button" aria-label="컴포넌트 검색" onClick={()=>input.current?.focus()}><Search size={18}/></button></header><main className="gallery"><div className="gallery-heading"><span className="eyebrow">SIXUN'S PLAYGROUND</span><h1>Un-common components.</h1><p>클릭하고, 드래그하고, 스크롤해 보세요.</p></div><div className="gallery-controls"><label className="gallery-search"><Search size={17}/><input ref={input} placeholder="Search components…" aria-label="컴포넌트 검색" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label><label className="filter-label">Category<select aria-label="카테고리" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{groups.map(([name])=><option key={name}>{name}</option>)}</select></label><label className="filter-label">Sort<select aria-label="정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="category">카테고리순</option><option value="newest">최신순</option><option value="number">번호순</option></select></label>{(query||category!=='All')&&<button className="clear-filter" onClick={()=>{setQuery('');setCategory('All')}}>초기화</button>}</div><p className="gallery-count">{filtered.length} components <span>· 103 demos available</span></p>
 {filtered.length===0?<div className="gallery-empty"><h2>검색 결과가 없습니다.</h2><button onClick={()=>{setQuery('');setCategory('All')}}>전체 컴포넌트 보기</button></div>:sort==='category'?groups.map(([name,ids])=>{const list=filtered.filter(i=>ids.includes(i.id));return list.length>0&&<section className="gallery-group" key={name}><h2>{name}<sup>[{list.length}]</sup></h2><p>Hover to preview · Click to interact</p><div className="component-grid">{list.map(i=><PreviewCard item={i} key={i.id}/>)}</div></section>}):<div className="component-grid sorted">{[...filtered].sort((a,b)=>sort==='newest'?b.id-a.id:a.id-b.id).map(i=><PreviewCard item={i} key={i.id}/>)}</div>}<div className="gallery-footer"><a href="/">©sixun</a><a href="#">Back to top ↑</a></div></main></>}
